#pragma once
#include <windows.h>

struct PacketInfo
{
	UINT32 ClientIndex = 0;
	UINT16 PacketId = 0;
	UINT16 DataSize = 0;
	char* pDataPtr = nullptr;
};

enum class  PACKET_ID : UINT16
{
	//SYSTEM
	SYS_USER_CONNECT = 11,
	SYS_USER_DISCONNECT = 12,
	SYS_END = 30,

	//DB
	DB_END = 199,

	//Client
	LOGIN_REQUEST = 201,
	LOGIN_RESPONSE = 202,

	PARTY_ENTER_REQUEST = 206,
	PARTY_ENTER_RESPONSE = 207, // 인원이 가득 차면 보내는 메시지

	PARTY_ORGANIZER_CHANGE_REQUEST = 209,

	PARTY_EXILE_REQUEST = 211,
	PARTY_EXILE_RESPONSE = 212,

	PARTY_LEAVE_REQUEST = 215,
	PARTY_LEAVE_RESPONSE = 216,

	PARTY_CHAT_REQUEST = 221,
	PARTY_CHAT_RESPONSE = 222,
	PARTY_CHAT_NOTIFY = 223,

	WHISPER_CHAT_REQUEST = 225,

	FRIEND_REQUEST = 241,
	FRIEND_RESPONSE = 242,

	FRIEND_DELETE_REQUEST = 243,
};