#pragma once
#include <string>
#include <vector>

struct FriendInfo {
	UINT32 userPkNum;
	std::string id;
	UINT16 userLevel=1;
	UINT16 partyIdx = 0;
	INT16 Check = 0; // 내가 검색할 땐 로그인 요청 확인, 친구 검색시에는 로그인 상태 확인
};

enum class ERROR_CODE : UINT16
{
	NONE = 0,

	LOGIN_USER_FULL = 31,
	LOGIN_USER_INVALID_ID = 32,
	LOGIN_USER_INVALID_PW = 33,
	LOGIN_USER_ALREADY = 34,

	FIND_NO_USER = 41,
	FIND_FRIEND_FAIL = 46,

	FRIEND_REQUEST_ALREADY = 51,
	FRIEND_REQUEST_FAIL = 52,
	FRIEND_REQUEST_CANCEL_FAIL = 53,

	FRIEND_DELETE_FAIL = 58,

	PARTY_MAKE_FAIL = 71,
	PARTYNUM_CHECK_FAIL = 72,
	PARTY_FULL = 73,
	PARTY_ENTER_FAIL = 74,

	// <friends>

	// <PARTY>
	//현재 파티원 다 차있어서 파티 참가 불가


	/*USER_MGR_INVALID_USER_INDEX = 11,
	USER_MGR_INVALID_USER_UNIQUEID = 12,

	/*NEW_ROOM_USED_ALL_OBJ = 41,
	NEW_ROOM_FAIL_ENTER = 42,

	ENTER_ROOM_NOT_FINDE_USER = 51,
	ENTER_ROOM_INVALID_USER_STATUS = 52,
	ENTER_ROOM_NOT_USED_STATUS = 53,
	ENTER_ROOM_FULL_USER = 54,

	ROOM_INVALID_INDEX = 61,
	ROOM_NOT_USED = 62,
	ROOM_TOO_MANY_PACKET = 63,

	LEAVE_ROOM_INVALID_ROOM_INDEX = 71,

	CHAT_ROOM_INVALID_ROOM_NUMBER = 81,*/
};